### ISSUE TITLE
Linux version of script?

### ISSUE THREAD

**Issue by a8underscore** [AndreVallestero/8mb-encoder#1]
hey, I run linux and this seems great. I would like to be able to use this :)

question: does this embed?

**Comment by AndreVallestero** [comment]
I don't think this will work on Linux unless a batch interpreter is implemented. I had plans to rewrite this in Python but I'm quite busy so that won't be happening for a while. I suggest you look at the calculations I use to specify 8MB and then encode your content using a better solution such as https://github.com/master-of-zen/Av1an
